version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
    groups:
      svelte:
        patterns:
          - "@sveltejs/*"
          - "svelte"
          - "svelte-check"
        update-types:
          - "minor"
          - "patch"
      sanity:
        patterns:
          - "@sanity/*"
          - "sanity"
        update-types:
          - "minor"
          - "patch"
      vite:
        patterns:
          - "vite"
          - "@sveltejs/vite-plugin-svelte"
        update-types:
          - "minor"
          - "patch"
      fonts:
        patterns:
          - "@fontsource*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
      - dependency-name: "svelte"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@sveltejs/*"
        update-types: ["version-update:semver-major"]
    allow:
      - dependency-type: "direct"
